{% extends 'layoutAdmin.phtml' %}
{% block content %}
	<link rel="stylesheet" href="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css">
	<link rel="stylesheet" href="/vendor/datatable_buttons/css/buttons.bootstrap.min.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.1.0/css/responsive.bootstrap.min.css">
	<style>
		.nav-condensed > li > a {
		   padding-top: 8px; 
		   padding-bottom: 8px; 
		}
		.navbar.navbar-mini {
			min-height: 40px;
			margin-bottom: 10px;

		}

		.navbar.no-radius {
			border-radius: 0;
		}
	</style>
    <h1>{{ title }}</h1>
	<table id="dataTable" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
		<thead>
			<th>Title</th>
			<th>Owner</th>
			<th>Date Start</th>
			<th>Date End</th>
			<th>Actions</th>
		</thead>
		<tbody>
			{% for event in events %}
				<tr>
					<td>{{ event.title }}</td>
					<td>{{ event.owner_id }}</td>
					<td>{{ event.date_start }}</td>
					<td>{{ event.date_end }}</td>
					<td>
						<button class="btn btn-xs btn-default">Edit</button>
						<button class="btn btn-xs btn-danger">Remove</button>
					</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
	
	<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>
	<script src="/vendor/datatable_buttons/js/dataTables.buttons.min.js"></script>
	<script src="https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.min.js"></script>
	<script src="/vendor/datatable_buttons/js/buttons.bootstrap.min.js"></script>
	<script src="/vendor/datatable_buttons/js/buttons.flash.min.js"></script>
	<script src="/vendor/datatable_buttons/js/buttons.colVis.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
	<script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
	<script src="//cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
	<script src="/vendor/datatable_buttons/js/buttons.html5.min.js"></script>
	<script src="//cdn.datatables.net/buttons/1.2.1/js/buttons.print.min.js"></script>
	

	<script>

		$(document).ready(function(){
			var myButton =  {
                text: 'Add Event',
                action: function ( e, dt, node, config ) {
                    alert( 'Button activated' );
                }
            };
			var table = $("#dataTable").DataTable({
				dom: "<'row'<'col-sm-6'B><'col-sm-6'f>>"+
						"<'row'<'col-sm-12'tr>>" +
						"<'row'<'col-sm-6'l><'col-sm-6'p>>"+
						"<'row'<'col-sm-12 text-center'i>>",
				buttons: [ 'copy', 'excel', 'pdf', myButton]
			});
			
		})

	</script>
{% endblock %}