{% extends 'layout.phtml' %}
{% block content %}
	<div class="col-md-6 col-md-offset-3">
    <h1>{{title}}</h1>
    <p><small>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloremque iste accusantium veritatis asperiores, sunt debitis odit laboriosam architecto facilis, laborum officia, quos ratione quae ad provident labore eius assumenda incidunt.</small></p>
    <p>{% include 'messages.phtml' %}</p>
	<form action="{{ path_for('event_invite') }}" class="form" method="POST">
		
		<div class="form-group">
			
		</div>
		<div class="form-group">
			<label for="">Recipient's Email</label>
			<input type="text" class="form-control" name="email" value="{{ email }}" placeholder="Email Address">
		</div>
		<div class="form-group">
			<div class="text-right">
			<button class="btn btn-primary">Send Invite</button></div>
		</div>
	</form>
	</div>
{% endblock %}