<html>

    <head>
        <!-- HEADER -->
        {% block head %}
            <meta charset="utf-8"/>
            <title>Slim 3</title>
            <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        {% endblock %}
    </head>
    <body>
        <!-- CONTENT -->
        <div class="container">
            {% block content %}Content{% endblock %}
        </div>
        <!-- FOOTER -->
        {% block footer %}{% endblock %}
    </body>
</html>
