<html>

    <head>
        <!-- HEADER -->
        {% block head %}
            <meta charset="utf-8"/>
            <title>{% if title is defined %}{{ title }}{% else %}Untitled{% endif %}</title>
            <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
            <script   src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
        {% endblock %}
    </head>
    <body>
        <!-- CONTENT -->
        <div class="container" id="{% if page_id is defined %}{{ page_id }}{% endif %}">
            {% block content %}Content{% endblock %}
        </div>
        <!-- FOOTER -->
        {% block footer %}{% endblock %}

        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    </body>
</html>
