{% extends 'layout.phtml' %}
{% block head %}
	{{ parent() }} {# This is extending the parent block which is "head" #}
{% endblock %}
{% block content %}
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<h1>{{ title }}</h1>
		</div>
	</div>
	<div class="row">

		<div class="col-md-6 col-md-offset-3">
			<p>
				{% include 'messages.phtml' %}
			</p>
			<form action="{{ path_for('login') }}" class="form" method="POST">
				<div class="form-group">
					<label for="">Email</label>
					<input type="text" class="form-control" name="email">
				</div>
				<div class="form-group">
					<label for="">Password</label>
					<input type="password" class="form-control" name="password">
				</div>
				<div class="form-group">
					<div class="col-md-9">Not a member? Register <a href="{{path_for('register')}}">here</a></div>
					<button class="btn col-md-3 btn-default" type="submit">Login</button>
					
				</div>
			</form>
		</div>
	</div>
    
{% endblock %}